apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guests
