apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId | dump}}
  {%- if values.description %}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - SpringBoot
    - Jenkins
    - Maven
spec:
  type: service
  lifecycle: experimental
  owner: guests
