pipeline {
    agent any
    tools {
        jdk 'jdk13'
        maven 'maven3'
    }
    stages {
        stage('Clone sources') {
            steps {
                git 'https://github.com/kiranbabu444'
            }
        }

        stage('Install') {
            steps {
                sh "mvn package"
            }
            post {
                always {
                    junit '**/target/*-reports/TEST-*.xml'
                    step([$class: 'JacocoPublisher',
                          execPattern: 'target/*.exec',
                          classPattern: 'target/classes',
                          sourcePattern: 'src/main/java',
                          exclusionPattern: 'src/test*'
                    ])
                }
            }
        }
    }
}
