apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: spring-boot-template
  title: Spring Boot Microservice
  description: A template for creating a Spring Boot service with Backstage
spec:
  owner: guests
  type: service

  parameters:
    - title: Enter project details
      required: 
        - component_id
      properties:
        component_id:
          title: Service Name
          type: string
          description: Name of the Spring Boot service
          ui:autofocus: true

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ../code-content
        values:
          componentId: ${{ parameters.component_id }}
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: "Generated Spring Boot service from Backstage template"
        #repoUrl: github.com/kiranbabu444/{{ parameters.component_id }}
        repoUrl: github.com?repo=${{ parameters.component_id }}&owner=kiranbabu444
        defaultBranch: main
        visibility: public
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml        

  output:
    links:
      - title: Repository
        url: https://github.com/kiranbabu444/{{ parameters.component_id }}
      - title: Open in Backstage
        url: /catalog/default/component/{{ parameters.component_id }}
