name: Register in Backstage

on:
  push:
    branches:
      - main

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Register Component
        uses: RoadieHQ/backstage-register-action@v1
        with:
          token: ${{ secrets.BACKSTAGE_TOKEN }}
          catalog-url: https://backstage.example.com/api/catalog/entities
          entity-path: catalog-info.yaml
